@startuml
left to right direction

actor User as user
package Restoran {
    actor Servant as serv
    actor Chief as chief

}

package Restoran {
    usecase "Pesan Menu" as U1
    usecase "Bayar Pesanan" as U2
    usecase "Melaporkan Pesanan" as U3
    usecase "Memasaak Pesanan" as U4
}


user --> U1
U1 --> serv
serv --> U3
U3 --> chief
chief --> U4
U4 --> user
user --> U2

@enduml
